image: docker:latest
services:
- docker:dind

stages:
  - test
  - build


test:
  stage: test
  before_script:
    - docker version
    - docker info
    - apt-get update -y
    - apt-get install software-properties-common
    - add-apt-repository ppa:duggan/bats --yes
    - apt-get update -y
    - >-
      apt-get install -y
      bats
      ldap-utils
  script:
    - make test

build-master:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
