image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_VERSION: 18.06.3~ce~3-0~ubuntu

stages:
  - test
  - build

build-test:
  stage: test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:bats" .
    - docker push "$CI_REGISTRY_IMAGE:bats"

test:
  stage: test
  image: ubuntu:latest
  before_script:
    - apt-cache madison docker-ce
    - apt-get -o Dpkg::Options::='--force-confnew' install -y --force-yes docker-ce=${DOCKER_VERSION}
    - apt-get update -y
    - apt-get install -y software-properties-common
    - add-apt-repository ppa:duggan/bats --yes
    - apt-get update -y
    - >-
      apt-get install -y
      bats
      ldap-utils
  script:
    - bats test-gitlab

build-master:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
